08/28/2024 18:55:27 - INFO - __main__ - Logging setup complete.
08/28/2024 18:55:28 - ERROR - root - Traceback (most recent call last):
08/28/2024 18:55:28 - ERROR - root -   File "/home/jiaruil5/personality/llm_personality/llm_bigfive/classifier/regressor_inference_expert_gen_test_data.py", line 44, in <module>
08/28/2024 18:55:28 - ERROR - root - test_dataset = load_from_disk(f'/data/user_data/wenkail/llm_personality/generator/data/outputs/generator_predictions_{trait}')#.select(range(100))
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root - ^
08/28/2024 18:55:28 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/datasets/load.py", line 2696, in load_from_disk
08/28/2024 18:55:28 - ERROR - root - raise FileNotFoundError(f"Directory {dataset_path} not found")
08/28/2024 18:55:28 - ERROR - root - FileNotFoundError
08/28/2024 18:55:28 - ERROR - root - :
08/28/2024 18:55:28 - ERROR - root - Directory /data/user_data/wenkail/llm_personality/generator/data/outputs/generator_predictions_c not found
