07/03/2024 00:58:32 - INFO - __main__ - Logging setup complete.
07/03/2024 00:58:37 - ERROR - root - Map:   0%|          | 0/50 [00:00<?, ? examples/s]
07/03/2024 00:58:37 - ERROR - root - Map: 100%|##########| 50/50 [00:00<00:00, 1004.44 examples/s]
07/03/2024 00:58:37 - ERROR - root - /data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/transformers/training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of ðŸ¤— Transformers. Use `eval_strategy` instead
  warnings.warn(
07/03/2024 00:58:37 - WARNING - accelerate.utils.other - Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
07/03/2024 00:58:38 - ERROR - root - /data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
07/03/2024 00:58:40 - ERROR - root - Traceback (most recent call last):
07/03/2024 00:58:40 - ERROR - root -   File "/home/jiaruil5/personality/llm_personality/llm_bigfive/classifier/classifier_inference_mse_newdata.py", line 100, in <module>
07/03/2024 00:58:40 - ERROR - root - predictions = trainer.predict(test_dataset)
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/transformers/trainer.py", line 3648, in predict
07/03/2024 00:58:40 - ERROR - root - output = eval_loop(
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/transformers/trainer.py", line 3757, in evaluation_loop
07/03/2024 00:58:40 - ERROR - root - loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/transformers/trainer.py", line 3981, in prediction_step
07/03/2024 00:58:40 - ERROR - root - outputs = model(**inputs)
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
07/03/2024 00:58:40 - ERROR - root - return self._call_impl(*args, **kwargs)
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
07/03/2024 00:58:40 - ERROR - root - return forward_call(*args, **kwargs)
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/accelerate/utils/operations.py", line 822, in forward
07/03/2024 00:58:40 - ERROR - root - return model_forward(*args, **kwargs)
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/accelerate/utils/operations.py", line 810, in __call__
07/03/2024 00:58:40 - ERROR - root - return convert_to_fp32(self.model_forward(*args, **kwargs))
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
07/03/2024 00:58:40 - ERROR - root - return func(*args, **kwargs)
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root -   File "/home/jiaruil5/personality/llm_personality/llm_bigfive/classifier/modeling_roberta.py", line 97, in forward
07/03/2024 00:58:40 - ERROR - root - print("output", outputs.logits)
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - ^
07/03/2024 00:58:40 - ERROR - root - AttributeError
07/03/2024 00:58:40 - ERROR - root - :
07/03/2024 00:58:40 - ERROR - root - 'BaseModelOutputWithPoolingAndCrossAttentions' object has no attribute 'logits'
